config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    post :confirm
    post :transfer
    post :reject
  end
  devise_for :acs
  devise_for :users
  root 'home#index'
  get 'users_home' => 'home#user_home'
  get 'acs_home' => 'home#acs_home'
  get 'abi' => 'home#abi'
  post 'settle_payment' => 'home#settle_payment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ac.rb
class Ac < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :request, dependent: :destroy
  has_many :payments, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :ac
  has_many :requests, dependent: :destroy
  has_many :user_notifications, dependent: :destroy
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :ac
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :order
  belongs_to :ac
  has_one :user_notification
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :user_notifications, dependent: :destroy
end

app/models/user_notification.rb
class UserNotification < ApplicationRecord
  belongs_to :user
  belongs_to :order
  belongs_to :request
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  def error(code='', message='')
    render json: { status: 'error', data: { code: code, message: message }}
    false
  end

  def ok(info={})
    render json: { status: 'ok', data: info }
    true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: :user_home
  before_action :authenticate_ac!, only: :acs_home

  def abi
    data = File.read("public/Election.json")
    return render :json => data
  end

  def index
    return redirect_to users_home_path if current_user
    return redirect_to acs_home_path if current_ac
  end

  def user_home
    @orders = Order.where(user_id: current_user.id)
    @uns = UserNotification.where(user_id: current_user.id, read: false)
  end

  def acs_home
    @c_requests = Request.where(ac_id: current_ac.id, done: false)
    @payments = Payment.where(ac_id: current_ac.id, done: false)
  end

  def settle_payment
    payment = Payment.find_by(id: params['pay_id'])
    payment.update(done: true)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :user_request_form]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
    if current_ac
      @cr = @order.requests.last
      @other_acs = Ac.all.where('id != ?', current_ac.id)
    end
  end

  def confirm
    order = Order.find(params['order_id'])
    request = Request.find_by(id: params['request_id'])

    # transfer confirm
    if order.ac_id != request.ac_id
      # create a payment request
      Payment.create(ac_id: order.ac_id, to: params['accountAddress'], amount: 1.0)
    end

    order.update(
      ac_id: request.ac_id,
      seat: request.seat,
      date: request.date,
      arrival: request.arrival,
      departure: request.departure,
    )

    is_execute = (params['is_execute'] == 'true')
    order.update(status: false)
    request.update(done: true, tx: params['tx'], is_execute: is_execute)
    UserNotification.create(user_id: order.user_id, order_id: order.id, request_id: request.id, isExecute: is_execute, read: false)

    ok
  end

  def reject
    order = Order.find(params['order_id'])
    request = Request.find_by(id: params['request_id'])
    request.update(done: true, is_execute: false)
    order.update(status: false)
    UserNotification.create(user_id: order.user_id, order_id: order.id, request_id: request.id, isExecute: false, read: false)

    ok
  end

  def transfer
    order = Order.find(params['order_id'])
    request = Request.find_by(id: params['requestID'])
    request.update(ac_id: params['airlineID'])

    ok
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    # send modified form to AC
    if current_user
      r = Request.new(order_params)
      r.order_id = @order.id
      r.save

      @order.update(status: true)

      respond_to do |format|
        format.html { redirect_to users_home_path, notice: 'Request was successfully submitted.' }
      end
    end

    # respond_to do |format|
    #   if @order.update(order_params)
    #     format.html { redirect_to @order, notice: 'Order was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @order }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @order.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :ac_id, :seat, :date, :arrival, :departure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/acs/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/acs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/home/acs_home.html.erb
<div class='red'><p id="notice"><%= notice %></p></div>

<div class="register-block">
  <button class="btn btn-success hide" id='register'>Register!</button>
  <button class="btn btn-outline-primary hide" id='already-register'>Already Register</button>
</div>

<div class='hide' id='unregister'>
  <br>
  <br>
  <br>
  <div class="form-group">
    <label>Enter the address you want to unregister</label>
    <br>
    <input id='unregister-address' placeholder="EX: 0x123sdjasdais23...">
    <br>
    <button id='unregister-btn' class="btn btn-danger">Unregister!</button>
  </div>
  <br>
  <br>
  <br>
</div>

<h1>AirLine Manager Page</h1>

<h2>Customer's Modified Request</h2>
<% @c_requests.each do |cr| %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Request ID</th>
      <th scope="col">Seat</th>
      <th scope="col">Date</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= cr.id %></td>
      <td><%= cr.seat %></td>
    <td><%= cr.date %></td>
      <td><%= cr.departure %></td>
      <td><%= cr.arrival%></td>
      <td><%= button_to 'Inspect', edit_order_path(cr.order_id), class: 'btn btn-success', method: :get %>
      </td>
    </tr>
  </tbody>
</table>
<% end %>


<h2>Payment request from partners</h2>
<% @payments.each do |payment| %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">To</th>
      <th scope="col">Amount(ether)</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= payment.to %></td>
      <td><%= payment.amount %></td>
      <td><button class="btn btn-primary" id='pay' payID=<%= payment.id %>  address=<%= payment.to %>>Pay</button></td>
    </tr>
  </tbody>
</table>

<% end %>

app/views/home/index.html.erb
<h1>Please login</h1>

<%= button_to 'Airline login', new_ac_session_path, method: :get, class: 'btn btn-primary' %>

<br>

<%= button_to 'Customer login', new_user_session_path, method: :get, class: 'btn btn-primary' %>

app/views/home/user_home.html.erb
<div class='red'><p id="notice"><%= notice %></p></div>

<% @uns.each do |un| %>
  <% if un.isExecute %>
    <% status = 'Proved' %>
  <% else%>
    <% status = 'Rejected' %>
  <% end %>
  <div class="alert alert-primary" role="alert">
    The OrderID <%= un.order_id %> has been <%= status %>
  </div>
<% end %>

<h1>Customer Manager Page</h1>
<h1>My order</h1>

<% @orders.each do |order| %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Airline</th>
      <th scope="col">Seat</th>
      <th scope="col">Date</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
      <th scope="col">Action</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.ac.name %></td>
      <td><%= order.seat %></td>
      <td><%= order.date %></td>
      <td><%= order.departure %></td>
      <td><%= order.arrival%></td>
      <td><%= button_to 'Modify', edit_order_path(order), method: :get, class: 'btn btn-danger' if !order.status? %> </td>
      <% if order.status? %>
        <td> <button class='btn btn-warning'>Wait for confirming</button> </td>
      <% end %>
    </tr>
  </tbody>
</table>
<% end %>


<script type="text/javascript">
  $.post('/', {param1: 'value1'}, function(data, textStatus, xhr) {
    /*optional stuff to do after success */
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airline</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user || current_ac %>
      <nav class="navbar navbar-dark bg-dark">
        <%= link_to "Home", root_path, class: 'navbar-brand' %>
        <p class='right white'><%= current_user.try(:email) || current_ac.try(:name) %> </p>
      </nav>
    <% end %>


    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field hide">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :order_user_id %>
  </div>

  <div class="field hide">
    <%= form.label :ac_id %>
    <%= form.number_field :ac_id, id: :order_ac_id %>
  </div>

  <div class="field">
    <%= form.label :seat %>
    <%= form.text_field :seat, id: :order_seat %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :order_date %>
  </div>

  <div class="field">
    <%= form.label :arrival %>
    <%= form.text_field :arrival, id: :order_arrival %>
  </div>

  <div class="field">
    <%= form.label :departure %>
    <%= form.text_field :departure, id: :order_departure %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<% if current_user %>
  <h1>Modified form</h1>
  <%= render 'form', order: @order %>
  <%= link_to 'Show', @order %> |
  <%= link_to 'Back', orders_path %>
<% else %>


  <div class='hide'>
  <!-- hidden value  -->
    <p id='request-id'><%= @cr.id %></p>
    <p id='order-id'><%= @order.id %></p>
  </div>

  <h2> user information: <%= @order.user.email %> </h2>

  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Type</th>
      <th scope="col">Airline Name</th>
      <th class='hide' scope="col">Airline ID</th>
      <th scope="col">Seat</th>
      <th scope="col">Date</th>
      <th scope="col">Departure</th>
      <th scope="col">Arrival</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Previous</td>
      <td><%= @order.ac.name %></td>
      <td class='hide'><%= @order.ac.id %></td>
      <td><%= @order.seat %></td>
      <td><%= @order.date %></td>
      <td><%= @order.departure %></td>
      <td><%= @order.arrival%></td>
    </tr>

     <tr class='red'>
      <td>New</td>
      <td><%= @cr.ac.name %></td>
      <td id='n-ac-id' class='hide'><%= @cr.ac_id %></td>
      <td id='n-seat'><%= @cr.seat %></td>
      <td id='n-date'><%= @cr.date %></td>
      <td id='n-departure' ><%= @cr.departure %></td>
      <td id='n-arrival'><%= @cr.arrival%></td>
    </tr>
  </tbody>
  </table>
<button class='btn btn-success' id='confirm'>Confirmt</button>
<button class='btn btn-warning' id='reject'>Reject</button>

<h2>Or Send to other Airlines</h2>
<% @other_acs.each do |ac| %>
  <input type="radio" name="airline" value=<%= ac.id %> > <%= ac.name %> <br>
<% end %>

<button id='transfer' class='btn btn-danger'> Transfer </button>
<% end %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Ac</th>
      <th>Seat</th>
      <th>Date</th>
      <th>Arrival</th>
      <th>Departure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user_id %></td>
        <td><%= order.ac_id %></td>
        <td><%= order.seat %></td>
        <td><%= order.date %></td>
        <td><%= order.arrival %></td>
        <td><%= order.departure %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @order.ac_id %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @order.seat %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
  <strong>Arrival:</strong>
  <%= @order.arrival %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @order.departure %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>